### DISCUSSION TITLE
Stack selector doesn't use the display values in blueprints

### DISCUSSION THREAD

**Discussion by jymden** [statamic-rad-pack/runway#184] [Help] [answered]
When configuring a has_many relationship and choosing one model to be able to select many others. The stack Selector uses the handle as column titles, not the display values. I've tried everything I can think of.  **Description** has display set to **Beskrivning** and **Claim Type Name** is set to **Typ**

Am I missing something?

Stack Selector:
![image](https://user-images.githubusercontent.com/4026726/202845364-0de2e63e-a2c0-4fc5-9e33-2439774a0614.png)

When going straight to the models own list view it uses the display values:
![image](https://user-images.githubusercontent.com/4026726/202845422-58c7c4e8-9177-46b4-8334-8972676cc552.png)

Here's the blueprint for the model in the stack selector:
```
hide: true
title: 'Claim'
sections:
  main:
    display: Main
    fields:
      -
        handle: description
        field:
          type: text
          validate:
            - required
          display: Beskrivning
          instructions_position: above
          listable: visible
          visibility: visible
          always_save: false
          input_type: text
          antlers: false
      -
        handle: claim_type_name
        field:
          type: text
          create: false
          display: Typ
          listable: visible
          visibility: visible
          always_save: false

```
