### DISCUSSION TITLE
title_format on belongs_to

### DISCUSSION THREAD

**Discussion by MacProFreak** [statamic-rad-pack/runway#233] [Help]
Hi,
I have a question about blueprints of the type "belongs_to" and the possibility to define title_format.
Is it possible to format title_format so that the related table can also be used?
I have this example

```yaml
      - handle: groups_id
        field:
          mode: select
          create: false
          display: 'group
          type: belongs_to
          icon: belongs_to
          instructions_position: above
          resource: academygroups
          max_items: 1
          with:
            - academyyears
          title_format: '{{ groups }} - {{ years }}'
```

The reference table academyyears contains the name of the year and I would like to output this in title_format, as the academygroups only contains the year ID.

Thanks for your support.

Best regards
Erich

**Comment by duncanmcclean** [comment]
Hey! 

What does your blueprint for the `academyyears` resource look like?

**Reply by MacProFreak** [reply]
Thanks for your fast answer. This looks like my academyyears blueprint

```yaml
sections:
  main:
    fields:
      -
        handle: year
        field:
          type: text
          display: 'Titel'
          validate: required
  sidebar:
    fields:
      - handle: created_at
        field:
          type: date
          mode: single
          time_enabled: true
          earliest_date: '2023-01-01'
          display: 'Erstellt am'
          read_only: true
          icon: date
          visibility: computed
          always_save: true
          format: 'Y-m-d H:i:s'
          listable: hidden
      - handle: updated_at
        field:
          type: date
          mode: single
          time_enabled: true
          earliest_date: '2023-01-01'
          display: 'Aktualisiert am'
          read_only: true
          icon: date
          visibility: computed
          always_save: true
          format: 'Y-m-d H:i:s'
          listable: hidden
```
