### DISCUSSION TITLE
Support '->' syntax for top-level Blueprint field handles

### DISCUSSION THREAD

**Discussion by morphsteve** [statamic-rad-pack/runway#301] [Feature Requests]
The use case would be to store Statamic-managed content data within a JSON blob on the record, rather than adding a new table column for each top-level Blueprint field.

For example:

```php
// migration
$table->json('content')->nullable();
```

```yml
# blueprint
fields:
  -
    handle: 'content->title'
    field:
      type: text
      ...
  -
    handle: 'content->body'
    field:
      type: bard
      ...
```

This seems like a fairly straightforward change. Laravel already supports setting a value in this way on a Model out of the box, provided the top-level attribute has a suitable cast:

```php
$model->{'content->title'} = '...';
```

Then I think we would just need to modify `ResourceController` [here](https://github.com/duncanmcclean/runway/blob/5.x/src/Http/Controllers/ResourceController.php#L169) to resolve the nested attribute:

```php
$value = data_get($record, str_replace('->', '.', $fieldKey));
```

We may also need to modify the conditions around lines 130 and 275 to avoid the JSON encode fallback if `$fieldKey` contains `'->'`.

I'm hoping I can test the concept and submit a PR in the next few weeks.
