### DISCUSSION TITLE
User Model resource showing roles and groups fields in edit form

### DISCUSSION THREAD

**Discussion by saqueib** [statamic-rad-pack/runway#304] [Help] [answered]
How to disable `groups` and `roles` fields options from form and list view. I haven't set these field blueprint. how do I disable these fields.

**User Blueprint**
```yaml
sections:
  main:
    fields:
      -
        handle: name
        field:
          type: text
          display: Name
          validate: required
      -
        handle: email
        field:
          type: text
          display: Email
          validate: required
      -
        handle: avatar
        field:
          type: text
          display: Avatar
          listable: false
          editable: false
      - handle: last_login
        field:
          type: date
          display: LastLogin
  sidebar:
    fields:
      -
        handle: created_at
        field:
          type: date
          display: CreatedAt
          listable: false
          editable: false
      -
        handle: updated_at
        field:
          type: date
          display: UpdatedAt

```

**Edit Form**
![user form](https://github.com/duncanmcclean/runway/assets/6937224/8f26c6da-8602-4982-8353-0d1369ff97e0)
