### DISCUSSION TITLE
How to display json field data

### DISCUSSION THREAD

**Discussion by saqueib** [statamic-rad-pack/runway#309] [Feature Requests]
Currently I have a `json` column which stores nested data. In blueprint its set to use `type: array`.

```yaml      -
        handle: meta
        field:
          type: array
          display: Meta
          listable: false
```
But when we open entry in Edit mode this only show first level value, rest looks `[object Object]`. 

![Screenshot 2023-08-03 at 12 12 13 PM](https://github.com/duncanmcclean/runway/assets/6937224/d295f60e-7dd6-4c70-aa37-ce51b218b1e1)

I have tried using `code` field but that shows it as empty box, tested with javascript and all other mode.

Is there anyway I can see the json values fully.

**Comment by duncanmcclean** [comment]
Yes, as of the [last release](https://github.com/duncanmcclean/runway/releases/tag/v5.1.0), you can now add fields to your blueprint for nested JSON data.

For example, say you have an `excerpt` inside your `meta` array, you could do this:

```yaml
fields:
  -
    handle: 'meta->excerpt'
    field:
      type: text
```

And provided you have a cast setup in your Eloquent model for the `meta` column, like this...

```php
protected $casts = [
    'values' => 'array', // or 'json', AsArrayObject::class
];
```

It should just work!

**Reply by saqueib** [reply]
Thanks @duncanmcclean I have updated to latest release and added following fields in my blueprint.

```yaml
      -
        handle: meta
        field:
          type: array
          display: Meta
          listable: false
      -
        handle: "meta->order"
        field:
            display: Order
            type: text
```

Result is still `[object Object]`

![Screenshot 2023-08-03 at 12 37 46 PM](https://github.com/duncanmcclean/runway/assets/6937224/df4f6a9e-dffa-4a09-90d9-170b2a30f21a)

here json value in db `meta` field 

```json
{
  "ip": "93.75.xxx.xx",
  "order": {
    "id": 71875,
    "notes": null,
    "terms": null,
    "title": "Order Form",
    "total": 97,
    "status": "PAID",
    "contact": {
      "id": 12,
      "email": "xxxxxx@gmail.com",
      "job_title": null,
      "last_name": "Novska",
      "first_name": "Anna",
      "company_name": ""
    }
  }
}
```

If I change the type of this nested field type to `array` it gives me `order.id` and all first level properties fine, but anything nested has same `[object Object]` problem. 

Its not possible to create fields for every nested props. I would suggest if we can have a json like code view. that will be best to edit and view the json. 

Not sure why type: code is giving empty value?
