### DISCUSSION TITLE
Asset field has no "Upload fileor drag & drop here to replace."

### DISCUSSION THREAD

**Discussion by martink635** [statamic-rad-pack/runway#384] [Help] [answered]
Hello,
my clients noticed the Runway asset field-type is a bit different from the regular collections. It is missing the "Upload fileor drag & drop here to replace." 

Is there any specific reason so I can give an explanation?

If this is something that can be added I'd gladly help out with a PR.

**Comment by duncanmcclean** [comment]
It should be exactly the same. Can you take a screenshot comparison of what you mean?

**Reply by martink635** [reply]
Definitely!

This is the one on "regular" collections, the classic asset field
<img width="679" alt="Screenshot 2023-12-07 at 22 37 28" src="https://github.com/duncanmcclean/runway/assets/444687/99f39b25-2ff4-4a7b-924f-f7e491011233">

This is how it looks on Runway collections.
<img width="299" alt="Screenshot 2023-12-07 at 22 37 42" src="https://github.com/duncanmcclean/runway/assets/444687/436a156f-4147-449b-9e9a-d173b68065e6">


Keep in mind both blueprints are exactly the same (the only difference is the display title)

**Reply by duncanmcclean** [reply]
Try adding `allow_uploads: true` to the Assets field in your blueprint.

**Reply by martink635** [reply]
Sadly I already have it:

```yaml
          - handle: logo
            field:
              mode: grid
              container: assets
              restrict: true
              allow_uploads: true
              max_files: 1
              type: assets
              listable: hidden
              display: Logo
```
