### DISCUSSION TITLE
Question about using Blade and Livewire components

### DISCUSSION THREAD

**Discussion by jolora** [statamic-rad-pack/runway#444] [Help] [answered]
### Description

HI all,

I'm conscious that this might seem like a stupid question but I've really not wrapped my head around augmentation yet, which I guess is at the heart of what I don't understand here.

I'm integrating Statamic into an existing Laravel site that is packed with Livewire and Blade components. For the most part the integration has been fine and we've continued using the main Blade layout component and used the `Statamic::tag` Blade directive throughout.

I've installed Runway so that editors can create relationships with some of the application's Eloquent models but I'm having trouble using the output of my first `has_many` fieldtype to any of our Blade components.

Here's what I'm trying in my Blade view:

```blade
@foreach($featured_listings as $listing)
    <livewire:listing-card :listing="$listing" :wire:key="$listing->id" simple="true" />
@endforeach
```

However, `$listing` is an array which obviously isn't compatible with the Livewire component.

This is the fieldtype definition:

```yaml
 -
  handle: featured_listings
  field:
    mode: default
    resource: listing
    create: true
    max_items: 2
    reorderable: true
    type: has_many
    display: 'Featured Listings'
    listable: hidden
    instructions_position: above
    visibility: visible
    replicator_preview: true
    hide_display: false
    with:
      - 'company'
```
What is the best way to go about using Runway fieldtypes to pass data into Livewire and Blade components?

Any advice would be greatly appreciated as I've been going in circles.

### Environment

Environment
Application Name: The Offsite Guide
Laravel Version: 9.52.16
PHP Version: 8.3.2
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: theoffsiteguide.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: log
Queue: redis
Scout: algolia
Session: redis

Statamic
Addons: 3
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.48.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
statamic-rad-pack/runway: 6.2.2
statamic/seo-pro: 5.4.1
