### DISCUSSION TITLE
Question about implementing Has Many fields on a Runway blueprint

### DISCUSSION THREAD

**Discussion by brizzo** [statamic-rad-pack/runway#458] [Help] [answered]
### Description

Hi. I was having some trouble getting a Has Many field working on one of my Runway blueprints. When attempting to create a new child record via the Has Many field, I kept getting a MySQL error that the foreign ID didn’t have a default value; presumably because it was not being set. The only way I could get the Has Many field to work was to implement a BelongsTo field on the related model’s blueprint.

Is it a requirement to implement both Has Many and Belongs To fields on each respective blueprint? Or should the Has Many field alone be capable of creating related models?

My HasMany/BelongsTo eloquent relationship is pretty standard; both relationships are configured correctly in the respective model classes. I’m just trying to gage if I’ve messed something up on my end regarding the Runway implementation.

Thanks for any guidance here.

### Environment

Environment
Application Name: Statamic
Laravel Version: 10.47.0
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.52.0 PRO

Statamic Addons
statamic-rad-pack/runway: 6.5.0

**Comment by duncanmcclean** [comment]
Can you share what your blueprint & eloquent model look like?

**Reply by brizzo** [reply]
Yes. I have Quiz and Question models with a HasMany/BelongsTo relationship:
```
class Quiz extends Model
{
    use HasFactory, HasRunwayResource;

    protected $fillable = [
        'title',
        'description',
    ];

    public function questions()
    {
        return $this->hasMany(Question::class);
    }
}
class Question extends Model
{
    use HasFactory, HasRunwayResource;

    protected $fillable = [
        'quiz_id',
        'question',
    ];

    public function quiz()
    {
        return $this->belongsTo(Quiz::class);
    }
}
```
Corresponding migrations:
```
Schema::create('quizzes', function (Blueprint $table) {
    $table->id();
    $table->string('title');
    $table->text('description');
    $table->timestamps();
});
Schema::create('questions', function (Blueprint $table) {
    $table->id();
    $table->foreignIdFor(Quiz::class)->index()->constrained()->cascadeOnDelete();
    $table->string('question');
    $table->timestamps();
});
```
Quiz blueprint:
```
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              input_type: text
              antlers: false
              type: text
              display: Title
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: description
            field:
              antlers: false
              type: textarea
              display: Description
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: questions
            field:
              mode: default
              resource: question
              create: true
              reorderable: false
              type: has_many
              display: Questions
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
title: Quiz
```
Question blueprint:
```
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: question
            field:
              input_type: text
              antlers: false
              type: text
              display: Question
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
title: Question
```
And here is the error I get when trying to create a new Question via the Questions has_many field. In this case, the quiz_id is not being set on the Question model.
![Screenshot 2024-03-12 at 11 00 32 AM](https://github.com/statamic-rad-pack/runway/assets/1663334/7e0aa811-6b70-4328-9ac2-2489d64d05d9)

Thanks for your help. Apologies if I'm missing something obvious here!

EDIT: Just to be clear, the parent Quiz record does already exist in the database when attempting to create a related Question.
