### DISCUSSION TITLE
Weird Runway Relationship for Specific Models

### DISCUSSION THREAD

**Discussion by dmmceldowney** [statamic-rad-pack/runway#514] [Help] [answered]
### Description

There's some weird behavior going on in my Statamic project and I'm not sure what the issue is, specifically. Hopefully there's just a single config line I missed somewhere that is causing this behavior.

I've got a table `service_provider_domains` that has a BelongsTo relationship with two tables: `service_providers` and `domains`. I've got my Laravel relationships defined with snake-case function names. However, I'm running into two issues.

1. I can't use the snake-case name for the function call and I get an error when I try to do so. To fix it, I have to remove the underscore altogether. If I do not, the table does not load in the Statamic CP and I get the following error, regardless of quotes: `Runway could not find [service_provider]`
2. After removing the underscore, the table successfully loads in the CP. *However*, the name field of the ServiceProvider does not show up; instead I just get a blank space. If I edit the record in the CP, the name properly shows up in the edit page and I can even pick a different one easily (awesome!). But it's not showing up in the table view, and I *need* it to show up there for this table to be useful (less awesome).

<img width="1051" alt="Screenshot 2024-06-05 at 1 36 39 PM" src="https://github.com/statamic-rad-pack/runway/assets/11196817/c4e9a4f3-f121-40f0-8779-19c3922de5b9">

**So, why doesn't snake-case work for the `resource` value in the blueprint and why doesn't it load the relationship properly in the table view?**

## Blueprint
```yaml
main:
    fields:
      -
        handle: id
        field:
          type: integer
          display: 'ID'
          visiblity: readonly
      -
        handle: service_provider_id
        field:
          max_items: 1
          mode: default
          resource: service_provider # changing to serviceprovider will load the page
          create: true
          display: 'Service Provider'
          type: 'belongs_to'
      -
        handle: domain_id
        field:
          max_items: 1
          mode: default
          resource: domain
          create: true
          display: 'Domain'
          type: 'belongs_to'
      -
```
edit: forgot to add the relationships for the ServiceProviderDomain

## ServiceProviderDomain relationships
```php
public function service_provider(): BelongsTo
{
    return $this->belongsTo(ServiceProviderDomain::class);
}

public function domain(): BelongsTo
{
        return $this->belongsTo(Domain::class);
}
```

### Environment

Environment
Application Name: Laravel
Laravel Version: 10.48.2
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.53.2 PRO

Statamic Addons
statamic-rad-pack/runway: 6.6.2
