### DISCUSSION TITLE
Not all fields on entries list are clickable

### DISCUSSION THREAD

**Discussion by IVoyt** [statamic-rad-pack/runway#522] [Help] [answered]
### Description

I have the following Blueprint and some of it's fields are not clickable on Entries list and I can not understand why. Are there any requirements to fields to be clickable?

```
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: type
            field:
              options:
                123: News
              type: select
              display: type
              localizable: false
              validate:
                - required
          -
            handle: translations_ua
            field:
              tab_icon: translate
              type: tab
              display: 'Translations UA'
              localizable: false
              listable: true
          -
            import: news_translations_ua
          -
            handle: translations_ru
            field:
              tab_icon: translate
              type: tab
              display: 'Translations RU'
              localizable: false
          -
            import: news_translations_ru
          -
            handle: translations_en
            field:
              tab_icon: translate
              type: tab
              display: 'Translations EN'
              localizable: false
          -
            import: news_translations_en
  sidebar:
    display: Sidebar
    sections:
      - {  }
title: News

```

here is the blueprint of one of fieldsets if needed
```
title: news_translations_ua
fields:
  -
    handle: title_ua
    field:
      type: text
      display: 'Title UA'
      localizable: false
      listable: true
      width: 50
      validate:
        - required
  -
    handle: slug_ua
    field:
      show_regenerate: true
      type: slug
      display: 'Slug UA'
      localizable: false
      listable: true
      from: title_ua
      width: 50
  -
    handle: body_ua
    field:
      type: tinymce_cloud
      display: 'Body UA'
      localizable: false
```

<img width="2090" alt="image" src="https://github.com/statamic/cms/assets/10925772/ee8a8f4a-6441-487d-ba53-dd7533f457b2">

### Environment

Environment
Application Name: TEST CMS
Laravel Version: 11.8.0
PHP Version: 8.2.13
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: test.cms.loc
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 6
Sites: 2 (TEST CMS 1, TEST CMS 2)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.2 PRO

Statamic Addons
eminos/statamic-tabs: 1.2.0
mitydigital/statamic-tinymce-cloud: 3.0.0
statamic-rad-pack/runway: 7.3.1
statamic/collaboration: 1.0.0
statamic/eloquent-driver: 4.0.0
statamic/ssg: 3.0.1

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Taxonomies: eloquent
Terms: eloquent

**Comment by duncanmcclean** [comment]
Runway will usually make the first field in the blueprint the "title field", so in your case that would be the "Type" field. Right now, you can probably click on that and it'll take you to the publish form page.

You can override the "title field" in your Runway config file:

```php
// config/runway.php

Product::class => [
    // ...
    'title_field' => 'translations_ua', // you can obviously change this
],
```

**Reply by IVoyt** [reply]
Thank you.
Well this does not seem convenient. What if I will change columns in "Customize columns" popup? I will need to change code then? Why would not make all fields clickable by default?

**Reply by IVoyt** [reply]
Also the suggestion does not work in my case. I specified field name "title_ua" from "news_translations_ua" fieldset and it didn't do the trick

**Reply by duncanmcclean** [reply]
> Well this does not seem convenient. What if I will change columns in "Customize columns" popup? I will need to change code then? Why would not make all fields clickable by default?

Because that's how it works with entries. If you hide the "Title" field, you'd have the same behaviour. You can always click into edit an entry via the dropdown on the right-hand side.

> Also the suggestion does not work in my case. I specified field name "title_ua" from "news_translations_ua" fieldset and it didn't do the trick

Can you provide the contents of your Runway config file?

**Reply by IVoyt** [reply]
> > Also the suggestion does not work in my case. I specified field name "title_ua" from "news_translations_ua" fieldset and it didn't do the trick
> 
> Can you provide the contents of your Runway config file?

here it is
```php
return [
    'resources' => [
        \App\Models\News::class => [
            'name' => 'News',
            'title_field' => 'title_ua',
            'cp_icon' => 'entries',
            'order_by' => 'created_at',
            'order_by_direction' => 'DESC',
            'route' => 'news/{{ id }}',
        ],
    ],

    'uris_table' => 'runway_uris',

    'disable_migrations' => false,

];
```

**Reply by duncanmcclean** [reply]
That's strange, it seems to be working fine on my test site:

<img width="1155" alt="image" src="https://github.com/statamic-rad-pack/runway/assets/19637309/fa4cccfc-6c11-451f-87df-2f4e6ac90ddb">

```php
Manufacturer::class => [
    'title_field' => 'slug',
],
```

Can you take a screenshot of the listing table?

**Reply by IVoyt** [reply]
Here you are
All the same

<img width="2109" alt="image" src="https://github.com/statamic-rad-pack/runway/assets/10925772/b895bbb3-5665-4f4e-a7a6-96ba5f5eddd6">

I expect in my case that the field Title UA would be clickable. The field is a part of fieldset (/cp/fields/fieldsets) and has a handle title_ua so I specified the "title_ua" as value for the "title_field" key in config/runway.php

**Reply by duncanmcclean** [reply]
> I expect in my case that the field Title UA would be clickable. The field is a part of fieldset (/cp/fields/fieldsets) and has a handle title_ua so I specified the "title_ua" as value for the "title_field" key in config/runway.php

Hmm, that should be the case now you're specifying the title field manually.

Can you share the YAML for the resource's blueprint?

**Reply by IVoyt** [reply]
> > I expect in my case that the field Title UA would be clickable. The field is a part of fieldset (/cp/fields/fieldsets) and has a handle title_ua so I specified the "title_ua" as value for the "title_field" key in config/runway.php
> 
> Hmm, that should be the case now you're specifying the title field manually.
> 
> Can you share the YAML for the resource's blueprint?

It is described in the first message. I can post it again

```yaml
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: type
            field:
              options:
                123: News
              type: select
              display: type
              localizable: false
              validate:
                - required
          -
            handle: translations_ua
            field:
              tab_icon: translate
              type: tab
              display: 'Translations UA'
              localizable: false
              listable: true
          -
            import: news_translations_ua
          -
            handle: translations_ru
            field:
              tab_icon: translate
              type: tab
              display: 'Translations RU'
              localizable: false
          -
            import: news_translations_ru
          -
            handle: translations_en
            field:
              tab_icon: translate
              type: tab
              display: 'Translations EN'
              localizable: false
          -
            import: news_translations_en
  sidebar:
    display: Sidebar
    sections:
      - {  }
title: News
```

Example of the importing fieldset is described in the first message as well
