### DISCUSSION TITLE
Using title_format on relationship fields

### DISCUSSION THREAD

**Discussion by jolora** [statamic-rad-pack/runway#678] [Help] [answered]
### Description

I have a question about title_formats on relationship fields such as HasMany. Is it possible to use a relations own relations in the title_format?

For example:

```
-
            handle: indicators
            field:
              resource: indicator
              relationship_name: indicators
              type: has_many
              display: Indicators
              title_format: 'Release: {{ release_id }} | Country: {{ country:name }}'
              with:
                - country
```

In this example, the Indicator model has two relations I'd like to use in the title formatting. For both release and country I'd like to use the "name" property. However, if I use {{ release:name }} or {{ country:name }} that area of the title remains blank. ( {{ release_id }} works fine in this example. It also seems to make no difference if I eager load the appropriate relations or not.

Am I missing something, is something not working as intended, or is this the expected behaviour?

### Environment

PHP 8.3
Runway 8.3.1
Statamic 5.52.0
Laravel 11.44.2
