### ISSUE TITLE
Computed fields not displaying in the front end

### ISSUE THREAD

**Issue by duncanmcclean** [statamic-rad-pack/runway#404]
### Discussed in https://github.com/statamic-rad-pack/runway/discussions/403

<div type='discussions-op-text'>

<sup>Originally posted by **mefenlon** January 15, 2024</sup>
I just upgraded from v5 to v6. I am now having issues with the computed fields displaying in the front end.
Using the dosumentation, https://runway.duncanmcclean.com/blueprints#content-computed-fields, I have an attribute defined in my model. On the backend, the blueprint is configured as computed and it displays just fine.
In my Model
```
    public function fullName(): Attribute
    {
        return Attribute::make(
            get: function () {
                return "{$this->display_title} {$this->sort_title}";
            }
        );
    }
```
In my blueprint
```
          -
            handle: full_name
            field:
              input_type: text
              antlers: false
              type: text
              display: Title
              icon: text
              listable: hidden
              instructions_position: above
              visibility: computed
              replicator_preview: true
              duplicate: false
              hide_display: false
```
In the front end, I am unable to list the attribute.
show.antlers.html
```
    {{ sort_title }} displays fine |
    {{ display_title }} displays fine |
    {{ full_name }} nothing
```</div>
