### ISSUE TITLE
Issue with GraphQL API when linking a model to a collection with the hasMany field type

### ISSUE THREAD

**Issue by thomas4Bitcraft** [statamic-rad-pack/runway#561]
### Description

I have a pages collection that uses a replicator fields for the different page modules. In one of the modules is a link to a runway model in Laravel. The problem is, that when I want to fetch the model over GraphQL it does not work and fails with the error: 

```
"errors": [
    {
      "message": "Internal server error",
      "locations": [
        {
          "line": 12,
          "column": 13
        }
      ],
      "path": [
        "entry",
        "modules",
        2,
        "leagues",
        0,
        "id"
      ],
      "extensions": {
        "debugMessage": "Call to a member function resolveGqlValue() on null",
        "file": "/home/vagrant/code/uptogame-cms/vendor/statamic-rad-pack/runway/src/GraphQL/ResourceType.php",
        "line": 52,
... }
]
```

Here is the collection blueprint:
```
title: Page
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: modules
            field:
              type: replicator
              display: Modules
              sets:
                new_module:
                  display: 'New Module'
                  sets:
                    calendar:
                      display: Calendar
                      icon: calendar-date
                      fields:
                        -
                          handle: title
                          field:
                            type: text
                            display: Title
                        -
                          handle: leagues
                          field:
                            resource: league
                            title_format: '{{ name }}'
                            type: has_many
                            display: Leagues
                            create: false
```

And here the query: 

```
query global {
  entry(collection: "pages", slug: "home") {
    ... on Entry_Pages_Page {
      id
      modules {
        ... on Set_Modules_Calendar {
          id
          title
          type
          leagues {
            id
          }
        }
      }
    }
  }
}
```

I was able to fix it temporarily by changing the mentioned function from this:
```
protected function resolver()
    {
        return function ($model, $args, $context, ResolveInfo $info) {
            if (! $model instanceof Model) {
                $resource = Runway::findResource(Str::replace('runway_graphql_types_', '', $info->parentType->name));

                $model = $resource->model()->firstWhere($resource->primaryKey(), $model);
            }

            return $model->resolveGqlValue($info->fieldName);
        };
    } 
```

To that: 
```
protected function resolver()
    {
        return function ($model, $args, $context, ResolveInfo $info) {
            if (! $model instanceof Model) {
                $resource = Runway::findResource(Str::replace('runway_graphql_types_', '', $info->parentType->name));

                $model = $resource->model()->firstWhere($resource->primaryKey(), $model[$resource->primaryKey()]->value());
            }

            return $model->resolveGqlValue($info->fieldName);
        };
    }
```

### Steps to reproduce

-

### Environment

Application Name: Statamic
Laravel Version: 11.15.0
PHP Version: 8.2.7
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.15.0 PRO

Statamic Addons
statamic-rad-pack/runway: 7.6.0
