### ISSUE TITLE
Fieldtype for hasOne relationship

### ISSUE THREAD

**Issue by lukabis** [statamic-rad-pack/runway#589]
### Description

Currently runway offers fieldtypes that support 'belongs to' and 'has many' relationships. I need a fieldtype that would be used for HasOne relationship. Currently, in my code I have to implement HasMany field type, limit 'maximum allowed entries' to 1. 

I have 2 models: Article and ArticlePackagingUnit. They have 1 to 1 relationship and method for that looks like this:

```php
/**
 * @return HasOne<ArticlePackagingUnit>
 */
public function articlePackagingUnit(): HasOne
{
    return $this->hasOne(ArticlePackagingUnit::class);
}
```

But for runway, for HasMany fieldtype, I also have to add this because there is no fieldtype for HasOne

```php
/**
 * For runway addon purposes. Article actually has only one packaging unit
 * but runway has only hasMany relationship field available
 *
 * @return HasMany<ArticlePackagingUnit>
 */
public function article_packaging_unit(): HasMany
{
    return $this->hasMany(ArticlePackagingUnit::class);
}
```

I could use belongsTo fieldtype on the model that has foreign key and I did. ArticlePackagingUnit has 'belongs to' field type on article_id field, but I really need to have _relationship field_ on the article model as well.

In article_packaging_unit blueprint:

```yaml
-
  handle: article_id
  field:
    resource: article
    create: false
    type: belongs_to
    display: Article
    listable: true
    visibility: read_only
    relationship_name: article
    title_format: '{{description_short}}'
```

In article blueprint:

```yaml
-
handle: article_packaging_unit
field:
  resource: article_packaging_unit
  relationship_name: article_packaging_unit
  create: false
  title_format: 'quantity per package: {{quantity_per_package_unit}} price per unit: {{price_per_unit}}'
  max_items: 1
  type: has_many
  display: 'Article Packaging Unit'
  visibility: read_only
```

### Steps to reproduce

1. create 2 models that have One to One relationship
2. create resources for those models in statamic runway
3. add HasMany fieldtype for that relationship in the blueprint of the model that **does not have** foreign key

### Environment

Environment
Application Name: Statamic
Laravel Version: 11.19.0
PHP Version: 8.3.11
Composer Version: 2.7.8
Environment: local
Debug Mode: ENABLED
URL: localhost:8080
Maintenance Mode: OFF
Timezone: Europe/Zurich
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / daily
Mail: log
Queue: sync
Scout: collection
Session: file

Locales
Installed: de, en, fr
LaravelLang\Lang\Plugin: 15.5.6
Locales Version: 2.9.2
Protected: de
Publisher Version: 16.4.0

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.7.1
PHP SDK Version: 4.8.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 4
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.19.0 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.3.0
statamic-rad-pack/runway: 7.7.3
statamic/eloquent-driver: 4.12.0
tv2regionerne/statamic-safeguard: 1.4.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: eloquent
