### ISSUE TITLE
Missing label in select/belongs_to field

### ISSUE THREAD

**Issue by edalzell** [statamic-rad-pack/runway#615]
### Description

I have a `belongs_to` field and the labels aren't showing up in the select drop down: 
![CleanShot 2024-09-26 at 14 18 44@2x](https://github.com/user-attachments/assets/7fabff82-578e-4913-9d16-15d982199b82)

### Steps to reproduce

Blueprint field:

```yaml
            handle: country_id
            field:
              mode: select
              resource: country
              display: Country
              type: belongs_to
              width: 50
              validate:
                - required
              localizable: false
              create: false
              title_format: '{{ name }}'
```

Resource config:

```php
        Country::class => [
            'name' => 'Countries',
            'blueprint' => 'country',
            'title_field' => 'name',
        ],
```

### Environment

Environment
Application Name: Zakat Foundation of America
Laravel Version: 11.25.0
PHP Version: 8.3.11
Composer Version: 2.7.7
Environment: local
Debug Mode: OFF
URL: zakat.test
Maintenance Mode: OFF
Timezone: America/Los_Angeles
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: redis
Session: file

Livewire
Livewire: v3.5.8

Statamic
Addons: 13
Sites: 4 (zakat.org (EN), zakat.org (AR), zfinstitute.com (ZFI), zakat.org (TR))
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.27.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.13.0
edalzell/forma: 3.0.1
jacksleight/statamic-bard-mutator: 2.3.1
jacksleight/statamic-distill: 0.8.0
jonassiewertsen/statamic-livewire: 3.8.0
statamic-rad-pack/runway: 7.10.0
statamic/seo-pro: 6.1.2
transformstudios/events: 5.4.3
transformstudios/front: 3.0.1
transformstudios/github: dev-main
transformstudios/neon: dev-1309-osp-log-error-454-throttling-failure-maximum-sending-rate-exceeded
transformstudios/review: 5.0
transformstudios/simple: 5.5.0
