### ISSUE TITLE
Has many relationship does not load existing values

### ISSUE THREAD

**Issue by janhenkes** [statamic-rad-pack/runway#624]
### Description

I have two models: Organization and OrganizationShippingAddress. On the Organization I have an HasMany relation for shipping addresses:

```php
public function shippingAddresses(): HasMany
{
   return $this->hasMany(OrganizationShippingAddress::class);
}
```

In the organization.yaml blueprint I created the following field:

```
tabs:
  shipping_addresses:
    display: 'Shipping addresses'
    sections:
        fields:
          -
            handle: shipping_addresses
            field:
              resource: organization_shipping_address
              relationship_name: shippingAddresses
              type: has_many
              display: 'Shipping addresses'
              sortable: false
```

I expect to see the existing related models, but they don't show. I can select other models and create new ones, but after I save the organization the related models do not show up in the field.

### Steps to reproduce

1. Create two models with an HasMany relationship
2. Add the HasMany field to model A
3. Create related models directly in the database
4. See if they show up in the field

### Environment

Fatal error: Uncaught Error: Class "App\Console\Kernel" not found in vendor/statamic/cms/src/Console/Please/Kernel.php:11

I use Statamic 5.31, Laravel 11.27 and Runway 7.11
